### PR TITLE
Improve homepage UI

### PR DESCRIPTION
**Pull request by tombui99**
https://github.com/SSWConsulting/SSW.CodeAuditor/issues/765

- Add a full stop at the end of each blurb (not the headings)
- Add padding to right-side of text section
- Align images/texts

image

### CODE REVIEW

**Comment by tiagov8** [comment]
Hi @tombui99 

1. On mobile the logo looks huge... Can you make sure the max-width is set to say 400px?

Screenshot 2023-11-13 at 9 56 55 AM

**Review by tiagov8 — CHANGES_REQUESTED** [review]
- [x] 1. Please action my comment https://github.com/SSWConsulting/SSW.CodeAuditor/pull/766#issuecomment-1808117594

**Comment by tombui99** [comment]
> Hi @tombui99
> 
> 1. On mobile the logo looks huge... Can you make sure the max-width is set to say 400px?
> 
> Screenshot 2023-11-13 at 9 56 55 AM

Hey @tiagov8 

The max width is already set to 400px.

I lowered it to 350px as per image below. Let me know what you think.

image

**Comment by tiagov8** [comment]
Hi @tombui99 

> The max width is already set to 400px.
> 
> I lowered it to 350px as per image below. Let me know what you think.

I am fine with 350, but if it is set to 400 it's NOT working... see this view where the logo is more than 700px wide:

Screenshot 2023-11-14 at 3 14 12 PM

**Comment by tombui99** [comment]
> Hi @tombui99
> 
> > The max width is already set to 400px.
> > I lowered it to 350px as per image below. Let me know what you think.
> 
> I am fine with 350, but if it is set to 400 it's NOT working... see this view where the logo is more than 700px wide:
> 

Hey @tiagov8 

Done - I have fixed the alignment issue so that image should stay consistent with max size set to 400px

image

**Pull request merged**
