### PR TITLE
Add artillery threshold

### PR DESCRIPTION
**Pull request by tombui99**

### CODE REVIEW

**Review by tombui99 — COMMENTED** [review]
Second "UI changes for threshold" commit: Added UI components for Artillery Report to show threshold setting and detail card

**Review by tombui99 — COMMENTED** [review]
New Artillery threshold modal component
image

**Review by william-liebenberg — APPROVED** [review]
Looks good

**Review by william-liebenberg — APPROVED** [review]
thanks for the modal updates

**Pull request merged**
